name: travelgpt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - nodejs=20          # includes npm
  - pip:
      - langchain
      - langgraph
      - langchain-openai
      - transformers
      - langchain-community
      - fastapi
      - llama-stack
      - torchao
      - uvicorn
      - wikipedia
      - langchain_huggingface
      - httpx
      - python-dotenv
      - pydantic
      - amadeus
      - requests